### ISSUE TITLE
No selector for CSS rule set

### ISSUE THREAD

**Issue by davidcmoulton** [stencila/thema#101]
- Loading a thema page in the browser shows invalid CSS (a rule set of `visibility:hidden` without a selector) within a `<style>` element. This is logged as a warning in the devtools console.
- It doesn't seem to make a difference which theme is selected

## Steps to reproduce
1. pull latest `next` branch (HEAD at the time of reporting is 672b7cef281ec5adea4f067e0ea947988b79f32c)
1. `npm install && npm run dev`
1. when the page loads in the browser, go into dev tools and observe the warning <img width="773" alt="Screenshot 2020-03-06 11 41 52" src="https://user-images.githubusercontent.com/2893480/76080750-84c28200-5f9f-11ea-8f33-d9afb1d43990.png">
1. viewing the DOM, this appears to be the cause: <img width="550" alt="Screenshot 2020-03-06 11 42 58" src="https://user-images.githubusercontent.com/2893480/76080873-cd7a3b00-5f9f-11ea-9063-678e031b426b.png">
1. in the browser, change the theme and note that this persists

I can't tell if this is having knock on effects i.e. are things being shown that shouldn't be.

**Comment by nokome** [comment]
There have been quite a lot of changes to the build of the demo app since 1.12.0 (https://github.com/stencila/thema/compare/v1.12.0...next) and this seems to have been fixed somewhere along the line. I no longer get the dev tools warning, nor the `<style data-styles="">` tag.

Closing, but of course feel free to reopen, if it still persists for you.

**Comment by alex-ketch** [comment]
The `.hydrated` class comes from [StencilJS](https://stenciljs.com), so likely comes from one of the Stencila WebComponent. The issue likely stems from there, and I'll investigate/track over there.
