### ISSUE TITLE
Add journal themes

### ISSUE THREAD

**Issue by jwijay** [stencila/thema#11]
Examples of journals to theme:
- https://www.bmj.com/content/366/bmj.l4673 (BMJ)
- https://www.embopress.org/doi/10.15252/embj.2018100825 (EMBO)
- https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-019-1393-7 (BMC Medicine, Springer Nature)
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0216270 (PLOS)

**Comment by nokome** [comment]
Closing this: I think we have enough examples of a variety of themes. New themes can be added as demanded.
