### ISSUE TITLE
How to access the article id?

### ISSUE THREAD

**Issue by davidcmoulton** [stencila/thema#113]
I need to access the id of an eLife article in order to be able to populate the lists introduced in https://github.com/stencila/thema/pull/111. I think it's represented by the data structure described at [https://github.com/stencila/thema/blob/next/src/examples/articleKitchenSink.json#L66](https://github.com/stencila/thema/blob/next/src/examples/articleKitchenSink.json#L66)(?) which is:
```
{
  ...
  "identifiers": [
    ...
    {
      "type": "PropertyValue",
      "name": "publisher-id",
      "propertyID": "https://registry.identifiers.org/registry/publisher-id",
      "value": "49574"
    },
    ...
  ]
  ...
```

It looks like the `identifiers` block maps to
```CSS
@custom-selector :--identifiers [data-itemprop~='identifiers'];
```
 in the generated `selectors.css`, but the individual identifier `publisher-id` doesn't have a selector.

Querying the DOM of each example artilce using e.g.
```JavaScript
const ids = first(':--identifiers')
console.log(':--identifiers', ids)
```
returns `null` in the browser in all cases, suggesting that no identifiers are coming through as yet.

Is my understanding correct? Is there something extra I need to do in order to get this data, or does it depend on a change to Encoda to expose it?

**Comment by nokome** [comment]
> Is my understanding correct? Is there something extra I need to do in order to get this data, or does it depend on a change to Encoda to expose it?

Yes, your understanding is correct, there needs to be an update in Encoda to expose that. I will try to do that today.

**Comment by nokome** [comment]
I have implemented this in Encoda. Now for an eLife article, the `identifiers` property of an `Article` originally decoded from JATS, gets encoded in HTML as:

```html
        <ul data-itemprop="identifiers">
          <li itemscope="" itemtype="http://schema.org/PropertyValue" itemprop="identifier">
            <meta itemprop="propertyID"
              content="https://registry.identifiers.org/registry/publisher-id"><span
              itemprop="name">publisher-id</span><span itemprop="value">50356</span></li>
          <li itemscope="" itemtype="http://schema.org/PropertyValue" itemprop="identifier">
            <meta itemprop="propertyID" content="https://registry.identifiers.org/registry/doi">
            <span itemprop="name">doi</span><span itemprop="value">10.7554/eLife.50356</span></li>
          <li itemscope="" itemtype="http://schema.org/PropertyValue" itemprop="identifier">
            <meta itemprop="propertyID"
              content="https://registry.identifiers.org/registry/elocation-id"><span
              itemprop="name">elocation-id</span><span itemprop="value">e50356</span></li>
        </ul>
```

I have tested this against https://search.google.com/structured-data/testing-tool/ and it looks good there:

![image](https://user-images.githubusercontent.com/1152336/77507998-814f5600-6ece-11ea-9d6a-5fd6f70b63da.png)

Note that the id `name` and `value` are spans so will be visible in all themes without some specific styling.

I shall follow up with a PR that upgrades the version of Encoda (which should be in the process of getting released as I write).
