### ISSUE TITLE
Add contrasting themes

### ISSUE THREAD

**Issue by nokome** [stencila/thema#173]
We currently have a fairly limited number of themes (compared to other theme libraries) and all of the themes look quite similar in the preview at https://stencila.github.io/thema/ . To me, it feels a little underwhelming.

It _should_, in theory, be pretty quick to create themes using classless CSS frameword (based on `skeleton`) that use these. There is a great project for previewing classless CSS frameworks: https://github.com/dohliam/dropin-minimal-css. The previewer, provides a quick way to, ummm, preview what they might look like. e.g.

- https://dohliam.github.io/dropin-minimal-css/?sakura
- https://dohliam.github.io/dropin-minimal-css/?latex
- https://dohliam.github.io/dropin-minimal-css/?ads-tufte
- https://dohliam.github.io/dropin-minimal-css/?splendor

**Comment by alex-ketch** [comment]
Closing as we have a more diverse library of themes. We can create new issues to add more themes as needed.
