### ISSUE TITLE
Code Chunks Block issue (eLife)

### ISSUE THREAD

**Issue by discodavey** [stencila/thema#182]
After updating the theme this morning the code chunks block does not finish after the code has stopped. It carries on down the page making the code chunks block very long.

<img width="1063" alt="Screenshot 2020-05-22 at 08 48 21" src="https://user-images.githubusercontent.com/745794/82644334-0f169b80-9c09-11ea-8918-a7d41c7f95e4.png">

**Comment by alex-ketch** [comment]
The upstream issue has been fixed: https://github.com/codemirror/codemirror.next/commit/73f046c8f364bb849b815f1b3ea6c25aa8c404dd

Will be fixed once a release is made and the package dependency updated.

**Comment by alex-ketch** [comment]
This was fixed by https://github.com/stencila/thema/pull/199
