### ISSUE TITLE
Suggested fixes to eLife theme

### ISSUE THREAD

**Issue by nokome** [stencila/thema#201]
This is just to note two issues with the current eLife theme. Both were previously identified by @FAtherden-eLife in https://github.com/elifesciences/issues/issues/5615#issuecomment-624639921. Both should be able to be fixed given the current HTML generated by Encoda.

![image](https://user-images.githubusercontent.com/1152336/85691398-96838d00-b728-11ea-8f5f-2508e95adde7.png)

1. Figure groups are represented in HTML as a `<ol itemscope="" itemtype="http://schema.org/Collection" data-usage="figGroup">` (with each figure being an `<li>`). The numbers for each `<li>` are redundant and should be hidden.

2. Previously the figure labels were missing. They are now part of the HTML (e.g. `<figure itemscope="" itemtype="http://schema.stenci.la/Figure" id="fig1" title="Figure 1."> <label data-itemprop="label">Figure 1.</label>...`) but are currently not styled in this theme.

**Comment by nlisgo** [comment]
I will create issues within our own project board to address these bugs and link to them here.

**Comment by nlisgo** [comment]
- https://github.com/elifesciences/issues/issues/5779
- https://github.com/elifesciences/issues/issues/5780

**Comment by alex-ketch** [comment]
The individual issues linked to by @nlisgo have been addressed and merged, closing.
