### ISSUE TITLE
Use kebab-case for theme names

### ISSUE THREAD

**Issue by nokome** [stencila/thema#32]
Currently, all themes names are all lowercase, except for `eLife`. 

![image](https://user-images.githubusercontent.com/1152336/74073403-160d0a00-4a6f-11ea-91cb-67f184657dea.png)

IMO, there would be less potential for errors if we had consistent casing. I propose using kebab-case.

**Comment by davidcmoulton** [comment]
The current build failure should be fixed when https://github.com/stencila/thema/pull/37 is merged.
