### ISSUE TITLE
Running tests locally stores 404 pages as reference screenshots

### ISSUE THREAD

**Issue by davidcmoulton** [stencila/thema#33]
Running the tests locally with `npm test` loads URIs on `localhost:3000` to generate reference screenshots. These pages all return 404 status codes, resulting in the 404 pages being stored as `reference` screen shots (also in `local`).

### Steps to reproduce
- `npm install`
- `npm run dev`
- ensure the directory `./test/screenshots/` is empty.
- run `npm test`.
- observe the browser windows controlled by web driver are loading URIs that result in 404 status:
<img width="575" alt="Screenshot 2020-02-10 16 14 41" src="https://user-images.githubusercontent.com/2893480/74167720-8b6c0c80-4c20-11ea-8ab4-487d65a80ccb.png">

- once the test run has finished, inspect the screenshots in `./test/screenshots/reference/` and observe that they are all of the respective 404 pages (the same is true in `./test/screenshots/local/`).

### Observations
- The local load of the pages on `localhost:3000` should work
- Is it worth considering putting a status check on the screenshot generation, so that it errors on a non-200 code, regardless of the screenshot match?

**Comment by alex-ketch** [comment]
Thanks for the bug report and the suggestions @davidcmoulton. There's a bit of a refactoring of the themes I'm aiming to wrap up early this week, and will address this issue next.

**Comment by nokome** [comment]
I've fixed this particular error: fb3ceb6b59165ed79083cf0bdb61ee886e4d33ef but tests still seem to be broken (styles are not getting loaded?).

> Is it worth considering putting a status check on the screenshot generation, so that it errors on a non-200 code, regardless of the screenshot match?

I had a quick look for  something that would do this. The closest I could find was https://webdriver.io/docs/api/chromium.html#setautoreporting but that seems to be Chrome specific?

**Comment by davidcmoulton** [comment]
@nokome Thanks for https://github.com/stencila/thema/commit/fb3ceb6b59165ed79083cf0bdb61ee886e4d33ef. It looks like the styles are not under the web root when the html files are loaded for the tests. For example during the test run the file loaded into the browser with the path `http://localhost:3000/article-antibodies.html`, references the CSS with

```HTML
<link href="../themes/stencila/styles.css" rel="stylesheet">
```

**Comment by davidcmoulton** [comment]
It looks like [HTTP status reporting won't be coming to WebDriver](https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/141). Could the HTTP status checks be put into some kind of preflight check that occurs before the WebDriver tests run? Then if the preflight fails, it's a hard fail before any screenshots are generated. This wouldn't be browser-specific.

**Comment by nokome** [comment]
> Could the HTTP status checks be put into some kind of preflight check that occurs before the WebDriver tests run?

That's a good idea IMO. I'm could add that to https://github.com/stencila/thema/blob/43c9cdd0be3a206cccb3173084e98bc12de72d54/test/screenshot.test.js#L24 later today. @alex-ketch ?
