### ISSUE TITLE
eLife theme regression

### ISSUE THREAD

**Issue by nokome** [stencila/thema#43]
This is just to document that in refactoring the `elife` theme to use the eLife pattern library (#30 ; now on the `next` branch) we have not-unexpected regressions and that the current version (on `master`) is, at time of writing, available at https://stencila.github.io/thema/ (with some screenshots below) and that the CSS for that is at https://github.com/stencila/thema/blob/c70dbb41f025a2a9a3fa3aca73113e05ae62fccc/src/themes/eLife/styles.css

When `next` is merged in to `master` a new version `2.0.0` will be published and https://stencila.github.io/thema/  will be updated with new eLife theme.

/cc @davidcmoulton in case it is of use.

![image](https://user-images.githubusercontent.com/1152336/74383363-ef2a4b80-4e53-11ea-974c-acfefc02eebf.png)

![image](https://user-images.githubusercontent.com/1152336/74383444-1123ce00-4e54-11ea-8ae9-6248011bd5bf.png)

![image](https://user-images.githubusercontent.com/1152336/74383473-213bad80-4e54-11ea-9787-5f50af82a684.png)

**Comment by davidcmoulton** [comment]
@nokome Thanks for the heads up 👍

**Comment by davidcmoulton** [comment]
Self-assigned as a reminder to keep an eye on it.

**Comment by nokome** [comment]
This issue is well passed it's used by date - regressions have been been fixed (and lots of improvements made!)
