### ISSUE TITLE
Extract resolveTheme and other Thema relevant functionality from Encoda

### ISSUE THREAD

**Issue by alex-ketch** [stencila/thema#47]
Currently utility functions around [Theme asset resolution ](https://github.com/stencila/encoda/blob/16902343111356e9b9a3a849a01455263c97b1a1/src/util/html.ts#L94) are fragmented across projects.
Encoda contains some logic, [Thema exposes ](https://github.com/stencila/thema/blob/next/src/themes/index.ts) some as well, and over time a conflict between the two groups has emerged.

@nokome proposed in consolidating all theme/Thema related functions in the Thema project.
Something to be mindful during this process will be to ensure that Node dependant functions do not leak into the browser targeted projects.

**Comment by nokome** [comment]
Closed by #65
