### ISSUE TITLE
feat(Theme builder): make it easier to create a theme from an existing one

### ISSUE THREAD

**Issue by nokome** [stencila/thema#55]
With the aim of encouraging contributed themes, we have a goal of making it easier to create themes, particularly for CSS-novices. One way to do that would be to have a "theme builder". Examples of these exist for other CSS frameworks e.g. https://bootstrap.build/

Things that such a builder would have:

- be able to use any of the existing themes as a **base theme**
  - we already have a select box for the theme
  - add a " :hammer:  Build your own theme based on this one" button
  - allow pinning to the current version of the base theme, or not
  - in the generated CSS and TS results in the 

- set any **theme variables** defined in the base theme
  - scan the base theme for any CSS variables and generate form inputs for each based on the 'type' of
    variable
  - tell authors if ":disappointed: Unfortunately, this theme does not expose any customisation variables"
  - in the browser, result sin the variable being set
  - in the generated CSS for the theme results in `---variable: value` being added

- add **extensions**
  - check box for extensions defined using CSS and/or JS e.g. `mathjax`, `citations-apa`, `citations-mla`, `stencila-components`
  - in browser results in CSS being enabled/disabled, JS being run for extension
  - in the generated CSS and TS files for the new theme results in:
      - `@import 'addon.css'` in the CSS
      - `import 'addon'` in the TS

- **save theme**:
  - at a minimum, allow to copy and paste of generated CSS and JS
  - ideally, use the Github API to submit a PR to this repo with the new theme as a folder with `styles.css`, `index.ts` and `README.md`

There are likely to be several open source libraries that are useful for many parts of this.

**Comment by alex-ketch** [comment]
After discussing, we decided to either exclude or simplify the following points from the initial version:

- > allow pinning to the current version of the base theme, or not
- > ideally, use the Github API to submit a PR to this repo with the new theme as a folder with styles.css, index.ts and README.md

**Comment by nokome** [comment]
After more discussion, we decided:

- not to allow turning off/on of extensions (this simplified several aspects and consistent with extensions really just being temporary in lieu of web components)
- add a button to create a "share link" with the values of the customized variables in it
- add a gallery page with thumbnail screenshots
- to investigate the Github PR idea further
