### ISSUE TITLE
Refine and document available theme extensions

### ISSUE THREAD

**Issue by alex-ketch** [stencila/thema#71]
- [x] Document in README what they are and how to use them @nokome
    - [x] Auto-generate a section that lists and links to README for each extension
- [ ] Citation style extensions
    - [ ] Needs a review of how we are generating HTML in Encoda (@nokome + @alex-ketch)
    - [ ] Revise / rewrite CSS for citations (@alex-ketch)
- [x] ~~Core Web Components extension (@alex-ketch)~~
    - [x] Ability to add/remove `@stencila/components` as an extension
    - [x] Currently always included as a wrapper
    - [x] See if can be dynamically loaded - add a `extension.json` that specifies resosureces to be

**Comment by nokome** [comment]
I'm starting on the first bullet point. After that the 3rd seems like the next step (it will shape the "what" and "how" of extensions so arguably could be considered 1st).

**Comment by nokome** [comment]
After some discussion we decided to scratch the third bullet point "Core Web Components extension". At present we expect that these will always be deployed with themes and it introduces a lot more complexity to try to make them optional beyond just _not_ including a tag for them in `<head>`.

**Comment by nokome** [comment]
To be unblock @davidcmoulton 's work on the elife theme as soon as possible, instead of making changes to Encoda, I'll use the DOM manipulation functions within extensions to get the desired markup structure. Those manipulations will then get 'ported' to Encoda soon.

PR for that later today.

**Comment by nokome** [comment]
Awaiting second review and merging of #84
