### ISSUE TITLE
How to treat the diff that npm install generates?

### ISSUE THREAD

**Issue by davidcmoulton** [stencila/thema#89]
Running `npm install` on the [current HEAD of the `next` branch](https://github.com/stencila/thema/commit/eddec645efeca448e2b699da50c30bb589cc0248) of thema results in [a diff](https://gist.github.com/davidcmoulton/769c56acf1cea296df2a952369662e08) of the `package.lock` and `src/examples/articleReadme.html` files. Should this diff be committed in its own PR? Incorporated into a wider PR? Discarded?

**Comment by nokome** [comment]
These are two separate issues...

- `package-lock.json`: yes, changes should be committed, it is commonly recommended to commit this file [e.g.](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) (although some disagree); I too am sometimes confused as to why diffs like this occur (differences in NPM version perhaps) but I don't think it's a problem to commit them

- `src/examples/articleReadme.html` (and other files) - all generated files are now ignored 059983d1a0e11cca1b1fa56cd849efcabbbb4b82 (not yet merged into `next` though)
